[2024-08-30T00:08:01.817+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-30T00:08:01.846+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_dag.extract_data manual__2024-08-30T00:07:59.148507+00:00 [queued]>
[2024-08-30T00:08:01.864+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_dag.extract_data manual__2024-08-30T00:07:59.148507+00:00 [queued]>
[2024-08-30T00:08:01.865+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 0
[2024-08-30T00:08:01.889+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): extract_data> on 2024-08-30 00:07:59.148507+00:00
[2024-08-30T00:08:01.900+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=517) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-30T00:08:01.902+0000] {standard_task_runner.py:72} INFO - Started process 519 to run task
[2024-08-30T00:08:01.904+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nyc_dag', 'extract_data', 'manual__2024-08-30T00:07:59.148507+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/nyc_dag_script.py', '--cfg-path', '/tmp/tmphkbn2p6k']
[2024-08-30T00:08:01.909+0000] {standard_task_runner.py:105} INFO - Job 61: Subtask extract_data
[2024-08-30T00:08:01.992+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_dag.extract_data manual__2024-08-30T00:07:59.148507+00:00 [running]> on host c8a3469a5a87
[2024-08-30T00:08:02.138+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='tolutosin16@gmail.org' AIRFLOW_CTX_DAG_OWNER='tolu_samuel' AIRFLOW_CTX_DAG_ID='nyc_dag' AIRFLOW_CTX_TASK_ID='extract_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-30T00:07:59.148507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-30T00:07:59.148507+00:00'
[2024-08-30T00:08:02.140+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-30T00:08:02.185+0000] {logging_mixin.py:190} INFO - An error occurred during extraction: [Errno 2] No such file or directory: '.\\dags\\raw_files\\EmpMaster.csv'
[2024-08-30T00:08:02.186+0000] {python.py:240} INFO - Done. Returned value was: (None, None, None, None, None)
[2024-08-30T00:08:02.225+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-30T00:08:02.226+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nyc_dag, task_id=extract_data, run_id=manual__2024-08-30T00:07:59.148507+00:00, execution_date=20240830T000759, start_date=20240830T000801, end_date=20240830T000802
[2024-08-30T00:08:02.281+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-30T00:08:02.296+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
