[2024-08-29T23:44:35.373+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-08-29T23:44:35.397+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: nyc_dag.clean_data manual__2024-08-29T23:44:29.545827+00:00 [queued]>
[2024-08-29T23:44:35.410+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: nyc_dag.clean_data manual__2024-08-29T23:44:29.545827+00:00 [queued]>
[2024-08-29T23:44:35.412+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 0
[2024-08-29T23:44:35.432+0000] {taskinstance.py:2879} INFO - Executing <Task(PythonOperator): clean_data> on 2024-08-29 23:44:29.545827+00:00
[2024-08-29T23:44:35.441+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=107) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-29T23:44:35.443+0000] {standard_task_runner.py:72} INFO - Started process 109 to run task
[2024-08-29T23:44:35.445+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'nyc_dag', 'clean_data', 'manual__2024-08-29T23:44:29.545827+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/nyc_dag_script.py', '--cfg-path', '/tmp/tmpfvry9p5h']
[2024-08-29T23:44:35.449+0000] {standard_task_runner.py:105} INFO - Job 30: Subtask clean_data
[2024-08-29T23:44:35.523+0000] {task_command.py:467} INFO - Running <TaskInstance: nyc_dag.clean_data manual__2024-08-29T23:44:29.545827+00:00 [running]> on host c8a3469a5a87
[2024-08-29T23:44:35.668+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='tolutosin16@gmail.org' AIRFLOW_CTX_DAG_OWNER='tolu_samuel' AIRFLOW_CTX_DAG_ID='nyc_dag' AIRFLOW_CTX_TASK_ID='clean_data' AIRFLOW_CTX_EXECUTION_DATE='2024-08-29T23:44:29.545827+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-29T23:44:29.545827+00:00'
[2024-08-29T23:44:35.671+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-08-29T23:44:35.691+0000] {logging_mixin.py:190} INFO - An error occurred during extraction: [Errno 2] No such file or directory: '.\\dags\\raw_files\\AgencyMaster.csv'
[2024-08-29T23:44:35.692+0000] {logging_mixin.py:190} INFO - Data extraction failed. Transformation aborted.
[2024-08-29T23:44:35.693+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-08-29T23:44:35.710+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-08-29T23:44:35.711+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=nyc_dag, task_id=clean_data, run_id=manual__2024-08-29T23:44:29.545827+00:00, execution_date=20240829T234429, start_date=20240829T234435, end_date=20240829T234435
[2024-08-29T23:44:35.782+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2024-08-29T23:44:35.800+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
